version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: coffee_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffee
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    networks:
      - coffee_network

volumes:
  postgres_data:

networks:
  coffee_network:
    driver: bridge
