apiVersion: v1
kind: Service
metadata:
  name: coffee-api
spec:
  type: NodePort
  selector:
    app: coffee
  ports:
    - port: 9090       # Cluster-internal port
      targetPort: 9090 # Container port
      nodePort: 30090  # NodePort on Minikube node

